### ISSUE TITLE
Essential documentation files

### ISSUE THREAD

**Issue by zenthm** [vorcle/vorcle#4]
## Description

This issue is dedicated to the addition of essential documentation files to the project, namely, `CHANGELOG.md`, `CODE_OF_CONDUCT.md`, `CONTRIBUTING.md`, `LICENSE.txt`, `README.md`, and `SECURITY.md`.

### Tasks

- [x] `CHANGELOG.md` file
- [x] `CODE_OF_CONDUCT.md` file
- [x] `CONTRIBUTING.md` file
- [x] `LICENSE.txt` file
- [x] `README.md` file
- [x] `SECURITY.md` file
